void flash_initialize(void);
unsigned char flash_databus_read(void);
void flash_databus_tristate(void);
void flash_databus_output(unsigned char data);
void flash_init(void);
void push_addr_bits(unsigned char bits);
void flash_chip_enable(void);
void flash_chip_disable(void);
void flash_output_enable(void);
void flash_output_disable(void);
void flash_setaddr(unsigned long int addr);
unsigned char flash_readcycle(unsigned long int addr);
void flash_read_init(void);
void flash_write_init(void);
unsigned char flash_readcycle_single(unsigned long int addr);
void flash_writecycle(unsigned long int addr, unsigned char data);
void flash_sector_write(unsigned int sector, unsigned char * buf);
void flash_sector_erase(unsigned int sector);
void flash_chip_erase(void);
inline unsigned long int formaddr24(unsigned int sect, unsigned char offset);
unsigned int identify_flash(void);
